env:
  browser: true
  es2021: true
  node: true
  "jest/globals": true
extends:
  - eslint:recommended
overrides:
  - files:
    - '**/*.ts'
    - '**/*.tsx'
    parser: "@typescript-eslint/parser"
    extends:
    - plugin:@typescript-eslint/recommended
    plugins:
    - "@typescript-eslint"
parser: '@typescript-eslint/parser'
plugins:
  - "jest"
parserOptions:
  ecmaVersion: latest
rules:
  indent:
    - error
    - 4
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - never
